#!/usr/bin/env node
// build-catalog.mjs - generate data/catalog.js from data/dataset.json in the
// exact export shape the app already imports, so the front end never changes.
// Provenance (evidence, edges, confidence) stays in dataset.json; the
// generated module carries only what the UI renders.
//
// Deterministic sanitation happens here as a second line of defense behind
// the validator: em/en dashes (banned by the test suite and routinely emitted
// by LLM distillation), missing fields, and bad enums all throw.
//
// Usage:
//   node scripts/build-catalog.mjs [data/dataset.json] [--out data/catalog.js]

import { readFileSync, writeFileSync } from "node:fs";

const DASH_RE = /[—–]/;

function clean(text, label) {
  if (typeof text !== "string" || !text.trim()) throw new Error(`${label}: empty text`);
  if (DASH_RE.test(text)) throw new Error(`${label}: em/en dash in "${text.slice(0, 60)}"`);
  return text.trim();
}

function lit(value) {
  return JSON.stringify(value);
}

export function generateCatalog(ds) {
  const meta = ds.meta || {};
  const careers = (ds.careers || []).map((c) => ({
    id: clean(c.id, "career id"),
    name: clean(c.name, `career ${c.id} name`),
    responsibilities: c.responsibilities.map((t, i) => clean(t, `career ${c.id} responsibility ${i}`)),
    skills: c.skills.map((t, i) => clean(t, `career ${c.id} skill ${i}`)),
  }));
  const careerIds = new Set(careers.map((c) => c.id));
  const dests = (list, label) =>
    list.map((d) => {
      if (!careerIds.has(d)) throw new Error(`${label}: unknown destination ${d}`);
      return d;
    });
  // Inferred destinations (adjacency judgment tier) are surfaced so the app can
  // render them softer; only those still present after edge resolution count.
  const inferredOf = (item) =>
    Array.isArray(item.inferred) ? item.inferred.filter((d) => (item.destinations || []).includes(d)) : [];
  const courses = (ds.courses || []).map((c) => {
    if (![1000, 2000, 3000].includes(c.level)) throw new Error(`course ${c.id}: bad level ${c.level}`);
    const out = {
      id: clean(c.id, "course id"),
      name: clean(c.name, `course ${c.id} name`),
      level: c.level,
      dept: clean(c.dept, `course ${c.id} dept`),
      destinations: dests(c.destinations, `course ${c.id}`),
    };
    const inf = inferredOf(c);
    if (inf.length) out.inferred = inf;
    return out;
  });
  const orgTypes = new Set((ds.meta || {}).orgTypes || ["MNC", "Small Business", "Startup"]);
  const internships = (ds.internships || []).map((i) => {
    if (!orgTypes.has(i.orgType))
      throw new Error(`internship ${i.id}: orgType ${JSON.stringify(i.orgType)} not in meta.orgTypes`);
    const out = {
      id: clean(i.id, "internship id"),
      role: clean(i.role, `internship ${i.id} role`),
      orgType: i.orgType,
      destinations: dests(i.destinations, `internship ${i.id}`),
    };
    const inf = inferredOf(i);
    if (inf.length) out.inferred = inf;
    // Validated-canonical roles carry their honesty marker into the app so the
    // UI can render them distinctly (diamond marker, chip badge, legend).
    if (i.grounding === "canonical") out.canonical = true;
    return out;
  });

  const block = (items) =>
    items
      .map((item) => {
        const fields = Object.entries(item)
          .map(([k, v]) => `    ${k}: ${lit(v)},`)
          .join("\n");
        return `  {\n${fields}\n  },`;
      })
      .join("\n");

  return `// catalog.js - GENERATED by scripts/build-catalog.mjs. Do not edit by hand;
// edit data/dataset.json (produced by the ground-catalog workflow) and rerun:
//
//   node scripts/build-catalog.mjs
//
// Generated ${meta.generatedAt || "(no timestamp)"} from run ${meta.runId || "(unknown)"}.
// Provenance for every node and edge lives in data/dataset.json.
//
// Edges are a verified skill-overlap heuristic over official course
// descriptions, live job postings, and the O*NET occupational database.
// That is requirement-side evidence, not measured student outcomes.
//
// This page includes information from O*NET Web Services and the O*NET
// database (${meta.onetVersion || "version unrecorded"}) by the U.S. Department
// of Labor, Employment and Training Administration (USDOL/ETA). Used under the
// CC BY 4.0 license. O*NET is a trademark of USDOL/ETA.

export const CAREERS = [
${block(careers)}
];

export const COURSES = [
${block(courses)}
];

export const INTERNSHIPS = [
${block(internships)}
];
`;
}

function main() {
  const args = process.argv.slice(2);
  const opt = (name, dflt) => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : dflt;
  };
  const file = args.find((a) => !a.startsWith("--")) || "data/dataset.json";
  const out = opt("--out", "data/catalog.js");
  const ds = JSON.parse(readFileSync(file, "utf8"));
  writeFileSync(out, generateCatalog(ds));
  console.log(`wrote ${out} (${ds.careers.length} careers, ${ds.courses.length} courses, ${ds.internships.length} internships)`);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  main();
}
